/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_pint.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals_cm33_core0 functional group */
/* BOARD_InitPeripherals_cm33_core0 defines for FLEXCOMM1 */
/* Definition of peripheral ID */
#define FLEXCOMM1_PERIPHERAL ((I2C_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define FLEXCOMM1_CLOCK_SOURCE 12000000UL
/* BOARD_InitPeripherals_cm33_core0 defines for PINT */
/* Definition of peripheral ID */
#define PINT_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* PINT interrupt vector ID (number). */
#define PINT_PINT_1_IRQN PIN_INT1_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_1_IRQ_PRIORITY 0
/* PINT interrupt vector ID (number). */
#define PINT_PINT_3_IRQN PIN_INT3_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_3_IRQ_PRIORITY 0
/* PINT interrupt vector ID (number). */
#define PINT_PINT_4_IRQN PIN_INT4_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_4_IRQ_PRIORITY 0
/* Definition of Slice ID for slice 0  */
#define PINT_SLICE_0 kPINT_PatternMatchBSlice0
/* Definition of Slice ID for slice 1  */
#define PINT_SLICE_1 kPINT_PatternMatchBSlice1
/* Definition of Slice ID for slice 2  */
#define PINT_SLICE_2 kPINT_PatternMatchBSlice2
/* Definition of Slice ID for slice 3  */
#define PINT_SLICE_3 kPINT_PatternMatchBSlice3
/* Definition of Slice ID for slice 4  */
#define PINT_SLICE_4 kPINT_PatternMatchBSlice4

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t FLEXCOMM1_config;
extern pint_pmatch_cfg_t PINT_SLICE_0_config;
extern pint_pmatch_cfg_t PINT_SLICE_1_config;
extern pint_pmatch_cfg_t PINT_SLICE_2_config;
extern pint_pmatch_cfg_t PINT_SLICE_3_config;
extern pint_pmatch_cfg_t PINT_SLICE_4_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* SLICE_1 callback function for the PINT component */
extern void cbENC_UP(pint_pin_int_t, uint32_t);
/* SLICE_3 callback function for the PINT component */
extern void cbENC_DW(pint_pin_int_t, uint32_t);
/* SLICE_4 callback function for the PINT component */
extern void cbENC_SW(pint_pin_int_t, uint32_t);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals_cm33_core0(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
